#### python packages

# https://discourse.nixos.org/t/installing-a-python-package-from-pypi/24553/2
# 不使用 fetchPypi，原因见上面链接
[musicdl]
fetch.github = "CharlesPikachu/musicdl"
src.git = "https://github.com/CharlesPikachu/musicdl"

[about-time]
src.pypi = "about-time"
fetch.pypi = "about-time"

[alive-progress]
fetch.pypi = "alive-progress"
src.pypi = "alive-progress"

[websocket-bridge-python]
fetch.pypi = "websocket_bridge_python"
src.pypi = "websocket_bridge_python"

[httpx]
src.github = "encode/httpx"
fetch.github = "encode/httpx"

[dict2xml]
src.github = "delfick/python-dict2xml"
fetch.github = "delfick/python-dict2xml"

[sd]
src.github_tag = "shanyouli/sd"
fetch.github = "shanyouli/sd"


### common

[mpvc]
src.github = "gmt4/mpvc"
fetch.github = "gmt4/mpvc"

[zpmod]
src.github = "z-shell/zpmod"
fetch.github = "z-shell/zpmod"

[maple-sc-nf]
src.github = "subframe7536/Maple-font"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/subframe7536/Maple-font/releases/download/v$ver/MapleMono-SC-NF.zip"

[maple-mono]
src.github = "subframe7536/Maple-font"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/subframe7536/maple-font/releases/download/v$ver/MapleMono-ttf.zip"

[lazyvim-star]
src.git = "https://github.com/LazyVim/starter"
fetch.github = "LazyVim/starter"

[go-musicfox]
src.github = "go-musicfox/go-musicfox"
fetch.github = "go-musicfox/go-musicfox"
git.fetchSubmodules = false
# passthru = { vendorHash = null }

[deeplx]
src.github = "OwO-Network/DeepLX"
fetch.github = "OwO-Network/DeepLX"

# [codicons]
# src.git = "https://github.com/microsoft/vscode-codicons"
# fetch.url = "https://github.com/microsoft/vscode-codicons/raw/$ver/dist/codicon.ttf"

[clash2singbox]
src.github = "xmdhs/clash2singbox"
fetch.github = "xmdhs/clash2singbox"

[musicn]
src.github = "zonemeen/musicn"
fetch.github = "zonemeen/musicn"

[userChromeJS]
src.git = "https://github.com/benzBrake/userChrome.js-Loader"
fetch.github = "benzBrake/userChrome.js-Loader"

[seam]
src.github = "Borber/seam"
fetch.github = "Borber/seam"
# passthru = { cargoHash = "sha256-SFwNYyZ/qzWlIwV2c8Tot+RyQtTNb559jK4GCGtWjNk=" }
cargo_locks = ["Cargo.lock"]

[fav]
src.github = "kingwingfly/fav"
fetch.github = "kingwingfly/fav"
cargo_locks = [ "Cargo.lock" ]

[bbdown]
src.git = "https://github.com/nilaoda/BBDown"
fetch.github = "nilaoda/BBDown"

[alist]
src.github = "alist-org/alist"
fetch.github = "alist-org/alist"

[alist-web]
src.github = "alist-org/alist-web"
fetch.url = "https://github.com/alist-org/alist-web/releases/download/$ver/dist.tar.gz"

### darwin
[yabai-zsh-completions]
src.git = "https://github.com/Amar1729/yabai-zsh-completions"
fetch.github = "Amar1729/yabai-zsh-completions"

[pngpaste]
src.github_tag = "jcsalterego/pngpaste"
fetch.github = "jcsalterego/pngpaste"

[dutis]
src.git = "https://github.com/tsonglew/dutis"
fetch.github = "tsonglew/dutis"
git.fetchSubmodules = false

[emacsclient]
src.git = "https://github.com/nashamri/spacemacs-logo"
fetch.url = "https://github.com/nashamri/spacemacs-logo/raw/$ver/spacemacs.icns"

[lporg]
src.github = "blacktop/lporg"
fetch.github = "blacktop/lporg"

[switchaudio-osx]
src.github_tag = "deweller/switchaudio-osx"
fetch.github = "deweller/switchaudio-osx"


### DarwinAPP
[quickrecorder]
src.github = "lihaoyun6/QuickRecorder"
fetch.url = "https://github.com/lihaoyun6/QuickRecorder/releases/download/$ver/QuickRecorder_v$ver.dmg"

[dashplayer]
src.github = "solidSpoon/DashPlayer"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/solidSpoon/DashPlayer/releases/download/v$ver/DashPlayer-$ver-arm64.dmg"

[airbattery]
src.github = "lihaoyun6/AirBattery"
fetch.url = "https://github.com/lihaoyun6/AirBattery/releases/download/$ver/AirBattery_v$ver.dmg"

[vimmotion]
src.github = "dwarvesf/VimMotionApp"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/dwarvesf/VimMotionApp/releases/download/v$ver/VimMotion.$ver.dmg"

[tmexclude]
src.github = "PhotonQuantum/tmexclude"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/PhotonQuantum/tmexclude/releases/download/v$ver/TimeMachine.Exclude_$ver_universal.dmg"

[chatgpt]
src.github="lencx/ChatGPT"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/lencx/ChatGPT/releases/download/v$ver/ChatGPT_$ver_macos_aarch64.dmg"

[next-chat]
src.github="ChatGPTNextWeb/ChatGPT-Next-Web"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/download/v$ver/NextChat_$ver_universal.dmg"

[clash-nyanpasu]
src.github="keiko233/clash-nyanpasu"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/keiko233/clash-nyanpasu/releases/download/v$ver/Clash.Nyanpasu_$ver_aarch64.dmg"

[clash-verge]
src.github="clash-verge-rev/clash-verge-rev"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v$ver/Clash.Verge_$ver_aarch64.dmg"

[any-reader]
src.github = "aooiuu/any-reader"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/aooiuu/any-reader/releases/download/v$ver/AnyReader-mac-arm64-$ver.dmg"

[neovide]
src.github="neovide/neovide"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/neovide/neovide/releases/download/$ver/Neovide-aarch64-apple-darwin.dmg"

[upic]
src.github="gee1k/uPic"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/gee1k/uPic/releases/download/v$ver/uPic.zip"

[zy-player]
src.github="Hiram-Wong/ZyPlayer"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/Hiram-Wong/ZyPlayer/releases/download/v$ver/zyplayer-mac-$ver-arm64.dmg"

[calibrepath]
src.github = "Cirn09/calibre-do-not-translate-my-path"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/Cirn09/calibre-do-not-translate-my-path/releases/download/v$ver/mac-patch-backend+update-v$ver.zip"

[calibre]
src.github = "Cirn09/calibre-do-not-translate-my-path"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://download.calibre-ebook.com/$ver/calibre-$ver.dmg"


# [vivaldi]
# src.webpage = "https://vivaldi.com/download"
# src.regex = "\"https://downloads.vivaldi.com/stable/Vivaldi.([0-9.]+).universal.dmg\""
# fetch.url = "https://downloads.vivaldi.com/stable/Vivaldi.$ver.universal.dmg"

[aerospace]
src.github_tag = "nikitabobko/AeroSpace"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/nikitabobko/AeroSpace/releases/download/v$ver/AeroSpace-v$ver.zip"

[ryujinx]
src.github = "Ryujinx/release-channel-master"
fetch.url = "https://github.com/Ryujinx/release-channel-master/releases/download/$ver/ryujinx-$ver-macos_universal.app.tar.gz"

[ryusak]
src.github = "FennyFatal/RyuSAK"
src.from_pattern = "v(.*)-experimental"
src.to_pattern = "\\1"
fetch.url = "https://github.com/FennyFatal/RyuSAK/releases/download/v$ver-experimental/RyuSAK-darwin-arm64-$ver.zip"

[spotube]
src.github = "KRTirtho/spotube"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/KRTirtho/spotube/releases/download/v$ver/Spotube-macos-universal.dmg"

[downkyi]
src.github = "yaobiao131/downkyicore"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/yaobiao131/downkyicore/releases/download/v$ver/DownKyi-$ver-osx-arm64.dmg"

[wiliwili]
src.github = "xfangfang/wiliwili"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/xfangfang/wiliwili/releases/download/v$ver/wiliwili-macOS-AppleSilicon.dmg"

[alexandria]
src.github = "btpf/Alexandria"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/btpf/Alexandria/releases/download/v$ver/Alexandria_$ver.0_x64.dmg"

### firefox-addons

[sidebery]
src.github = "mbnuqw/sidebery"
fetch.github = "mbnuqw/sidebery"

[darkreader]
src.github = "darkreader/darkreader"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/darkreader/darkreader/releases/download/v$ver/darkreader-firefox.xpi"


### packages in modules
[qbittorrent]
src.github = "c0re100/qBittorrent-Enhanced-Edition"
fetch.github = "c0re100/qBittorrent-Enhanced-Edition"

[yabai]
src.github = "koekeishiya/yabai"
fetch.github = "koekeishiya/yabai"

[yabai-bin]
src.github = "koekeishiya/yabai"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/koekeishiya/yabai/releases/download/v$ver/yabai-v$ver.tar.gz"

["emacs29.role-patch"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/fix-window-role.patch"

["emacs29.poll"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-29/poll.patch"

["emacs29.round-undecorated-frame"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-29/round-undecorated-frame.patch"

["emacs29.system-appearance"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/system-appearance.patch"

["emacs29.no-frame-refocus-cocoa"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/no-frame-refocus-cocoa.patch"

["emacs30.role-patch"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/fix-window-role.patch"

["emacs30.poll"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-30/poll.patch"

["emacs30.round-undecorated-frame"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-30/round-undecorated-frame.patch"

["emacs30.system-appearance"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-30/system-appearance.patch"
