### Don't use Chinese, I don't know what causes using Chinese comments to report an error.

#### python packages

[about-time]
src.pypi = "about-time"
fetch.pypi = "about-time"

[alive-progress]
fetch.pypi = "alive-progress"
src.pypi = "alive-progress"

[dict2xml]
src.github = "delfick/python-dict2xml"
fetch.github = "delfick/python-dict2xml"

[httpx]
src.github = "encode/httpx"
fetch.github = "encode/httpx"

# https://discourse.nixos.org/t/installing-a-python-package-from-pypi/24553/2
# The reason for not using fetch.pypi is referenced above
[musicdl]
fetch.github = "CharlesPikachu/musicdl"
src.git = "https://github.com/CharlesPikachu/musicdl"

[sd]
# src.github_tag = "shanyouli/sd"
src.git = "https://github.com/shanyouli/sd"
fetch.github = "shanyouli/sd"

[websocket-bridge-python]
fetch.pypi = "websocket_bridge_python"
src.pypi = "websocket_bridge_python"

### common

["bash-env-json"]
src.github = "tesujimath/bash-env-json"
fetch.url = "https://github.com/tesujimath/bash-env-json/raw/$ver/bash-env-json"

[bbdown]
src.git = "https://github.com/nilaoda/BBDown"
fetch.github = "nilaoda/BBDown"

[clash2singbox]
src.github = "xmdhs/clash2singbox"
fetch.github = "xmdhs/clash2singbox"

[deeplx]
src.github = "OwO-Network/DeepLX"
fetch.github = "OwO-Network/DeepLX"

[fav]
src.github = "kingwingfly/fav"
fetch.github = "kingwingfly/fav"
cargo_locks = [ "Cargo.lock" ]

[go-musicfox]
src.github = "go-musicfox/go-musicfox"
fetch.github = "go-musicfox/go-musicfox"
git.fetchSubmodules = false
# passthru = { vendorHash = null }

# a fast CLI documentaion searcher for nix
[manix]
src.git = "https://github.com/kaii-zen/manix"
fetch.github = "kaii-zen/manix"
cargo_locks = ["Cargo.lock"]

[musicn]
src.github_tag = "zonemeen/musicn"
fetch.github = "zonemeen/musicn"

[pragmasevka]
src.github = "shanyouli/iosevka"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/shanyouli/iosevka/releases/download/v$ver/pragma-sevka-mono.zip"

[pragmasevka-nerd]
src.github = "shanyouli/iosevka"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/shanyouli/iosevka/releases/download/v$ver/pragma-sevka-mono-nerd.zip"

[pragmasevka-sans]
src.github = "shanyouli/iosevka"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/shanyouli/iosevka/releases/download/v$ver/pragma-sevka-sans.zip"

[pragmasevka-serif]
src.github = "shanyouli/iosevka"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/shanyouli/iosevka/releases/download/v$ver/pragma-sevka-serif.zip"

[pragmasevka-sc]
src.github = "shanyouli/iosevka"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/shanyouli/iosevka/releases/download/v$ver/Pragma-Sevka-SC.ttf"

[pragmasevka-sc-nf]
src.github = "shanyouli/iosevka"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/shanyouli/iosevka/releases/download/v$ver/Pragma-Sevka-SC-NF.ttf"

[qbittorrent]
src.github = "c0re100/qBittorrent-Enhanced-Edition"
fetch.github = "c0re100/qBittorrent-Enhanced-Edition"

[rime-ice]
src.git = "https://github.com/iDvel/rime-ice.git"
fetch.github = "iDvel/rime-ice"

# [rime-wanxiang]
# src.github_tag = "amzxyz/rime_wanxiang_pro"
# src.from_pattern = "v(.*)"
# src.to_pattern = "\\1"
# fetch.url = "https://github.com/amzxyz/rime_wanxiang_pro/releases/download/v$ver/wanxiang-moqi-fuzhu.zip"

[sarasa-term]
src.github = "laishulu/Sarasa-Term-SC-Nerd"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v$ver/SarasaTermSCNerd.ttc.tar.gz"

[seam]
src.github = "Borber/seam"
fetch.github = "Borber/seam"
cargo_locks = ["Cargo.lock"]

[singboxp]
fetch.github = "PuerNya/sing-box"
src.git = "https://github.com/PuerNya/sing-box"

[tmux-fastcopy]
src.github = "abhinav/tmux-fastcopy"
fetch.github = "abhinav/tmux-fastcopy"

[userChromeJS]
src.git = "https://github.com/benzBrake/userChrome.js-Loader"
fetch.github = "benzBrake/userChrome.js-Loader"

# rime 輸入法的語法模型。
# [wanxiang-lts-zh-hans]
# src.manual = "2024"
# fetch.url = "https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram"

[zpmod]
src.github = "z-shell/zpmod"
fetch.github = "z-shell/zpmod"

### darwin

[aerospace]
src.github_tag = "nikitabobko/AeroSpace"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/nikitabobko/AeroSpace/releases/download/v$ver/AeroSpace-v$ver.zip"

[borders]
src.github = "FelixKratz/JankyBorders"
fetch.github = "FelixKratz/JankyBorders"

[dutis]
src.git = "https://github.com/tsonglew/dutis"
fetch.github = "tsonglew/dutis"
cargo_locks = ["Cargo.lock"]
git.fetchSubmodules = false

[emacsclient]
src.git = "https://github.com/nashamri/spacemacs-logo"
fetch.url = "https://github.com/nashamri/spacemacs-logo/raw/$ver/spacemacs.icns"

[lporg]
src.github = "blacktop/lporg"
fetch.github = "blacktop/lporg"

[mac-app-util]
src.git = "https://github.com/hraban/mac-app-util"
fetch.url = "https://github.com/hraban/mac-app-util/raw/$ver/main.lisp"

[mkalias]
src.github_tag = "reckenrode/mkAlias"
fetch.github = "reckenrode/mkAlias"
cargo_locks = ["Cargo.lock"]

[nowplaying-cli]
src.github = "kirtan-shah/nowplaying-cli"
fetch.github = "kirtan-shah/nowplaying-cli"

[pngpaste]
src.github_tag = "jcsalterego/pngpaste"
fetch.github = "jcsalterego/pngpaste"

[switchaudio-osx]
src.github_tag = "deweller/switchaudio-osx"
fetch.github = "deweller/switchaudio-osx"

# [vivaldi]
# src.webpage = "https://vivaldi.com/download"
# src.regex = "\"https://downloads.vivaldi.com/stable/Vivaldi.([0-9.]+).universal.dmg\""
# fetch.url = "https://downloads.vivaldi.com/stable/Vivaldi.$ver.universal.dmg"

[yabai-zsh-completions]
src.git = "https://github.com/Amar1729/yabai-zsh-completions"
fetch.github = "Amar1729/yabai-zsh-completions"

### firefox-addons

[darkreader]
src.github = "darkreader/darkreader"
src.from_pattern = "v(.*)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/darkreader/darkreader/releases/download/v$ver/darkreader-firefox.xpi"

[sidebery]
src.github = "mbnuqw/sidebery"
fetch.github = "mbnuqw/sidebery"

[zeroomega]
src.github = "zero-peak/ZeroOmega"
# src.from_pattern = "v(.*)"
# src.to_pattern = "\\1"
fetch.url = "https://github.com/zero-peak/ZeroOmega/releases/download/$ver/zeroomega-$ver.xpi"

### packages in modules

#### emacs
["emacs29.no-frame-refocus-cocoa"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/no-frame-refocus-cocoa.patch"

["emacs29.role-patch"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/fix-window-role.patch"

["emacs29.round-undecorated-frame"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-29/round-undecorated-frame.patch"

["emacs29.system-appearance"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/system-appearance.patch"

["emacs30.role-patch"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-28/fix-window-role.patch"

["emacs30.round-undecorated-frame"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-30/round-undecorated-frame.patch"

["emacs30.system-appearance"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-30/system-appearance.patch"

["emacs31.round-undecorated-frame"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-31/round-undecorated-frame.patch"

["emacs31.system-appearance"]
src.git = "https://github.com/d12frosted/homebrew-emacs-plus"
fetch.url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/$ver/patches/emacs-31/system-appearance.patch"

#### fish plugins
["fisher"]
src.github = "jorgebucaran/fisher"
fetch.github = "jorgebucaran/fisher"

#### lau packages
[antifennel]
src.git = "https://git.sr.ht/~technomancy/antifennel"
fetch.git = "https://git.sr.ht/~technomancy/antifennel"

[jeejah-rock]
src.webpage = "https://luarocks.org/modules/technomancy/jeejah"
src.regex = "href=\"/modules/technomancy/jeejah/([0-9.-]+)"
fetch.url = "https://luarocks.org/manifests/technomancy/jeejah-$ver.rockspec"

[jeejah]
src.git = "https://gitlab.com/technomancy/jeejah"
fetch.git = "https://gitlab.com/technomancy/jeejah"
# src.webpage = "https://gitlab.com/technomancy/jeejah/-/tags"
# src.regex = "href=\"/technomancy/jeejah/-/tags/([0-9.]+)"
# fetch.tarball = "https://gitlab.com/technomancy/jeejah/-/archive/$ver/jeejah-$ver.tar"
