# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aerospace = {
    pname = "aerospace";
    version = "0.19.2-Beta";
    src = fetchurl {
      url = "https://github.com/nikitabobko/AeroSpace/releases/download/v0.19.2-Beta/AeroSpace-v0.19.2-Beta.zip";
      sha256 = "sha256-u4UBOxgYmWPh/ASeHU3yg/zCV1EVYVdHY469LvhapHA=";
    };
  };
  alive-progress = {
    pname = "alive-progress";
    version = "3.3.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/alive-progress/alive-progress-3.3.0.tar.gz";
      sha256 = "sha256-RX3SQotI2s1JhUAipGRI0jakjxtyd4dAccOTlTB+gww=";
    };
  };
  antifennel = {
    pname = "antifennel";
    version = "cea2f62b71c53eeb2bfe056625a87f1a9ddfcddf";
    src = fetchgit {
      url = "https://git.sr.ht/~technomancy/antifennel";
      rev = "cea2f62b71c53eeb2bfe056625a87f1a9ddfcddf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LPQLxq7WQHi6CXgdYy6FKz04efFT5p6xPwDx5qhAw50=";
    };
    date = "2025-10-05";
  };
  bash-env-json = {
    pname = "bash-env-json";
    version = "0.7.0";
    src = fetchurl {
      url = "https://github.com/tesujimath/bash-env-json/raw/0.7.0/bash-env-json";
      sha256 = "sha256-6x8zErIYZuk3qWB807rNVbvH9ZLl8cGffJnKrt7DlSg=";
    };
  };
  bbdown = {
    pname = "bbdown";
    version = "4b47d1bc1752a1385604a8e388054aa5dcc667a7";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "4b47d1bc1752a1385604a8e388054aa5dcc667a7";
      fetchSubmodules = false;
      sha256 = "sha256-y4m92lAaIOsbHUCEtvz4s1zXxo4cPYmdX+vZtpuDenU=";
    };
    date = "2025-09-07";
  };
  borders = {
    pname = "borders";
    version = "v1.8.4";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "JankyBorders";
      rev = "v1.8.4";
      fetchSubmodules = false;
      sha256 = "sha256-31Er+cUQNJbZnXKC6KvlrBhOvyPAM7nP3BaxunAtvWg=";
    };
  };
  clash2singbox = {
    pname = "clash2singbox";
    version = "v0.1.4";
    src = fetchFromGitHub {
      owner = "xmdhs";
      repo = "clash2singbox";
      rev = "v0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-qEv5lmuu4UWaxmCQ0sb21TMJVhYaW7VscD6O+dOWjgE=";
    };
  };
  darkreader = {
    pname = "darkreader";
    version = "4.9.110";
    src = fetchurl {
      url = "https://github.com/darkreader/darkreader/releases/download/v4.9.110/darkreader-firefox.xpi";
      sha256 = "sha256-kBC2WdbvGj5kjCCBSaM62vwzktNJkGHsBw4akovI0OA=";
    };
  };
  deeplx = {
    pname = "deeplx";
    version = "v1.0.9";
    src = fetchFromGitHub {
      owner = "OwO-Network";
      repo = "DeepLX";
      rev = "v1.0.9";
      fetchSubmodules = false;
      sha256 = "sha256-aJZ6DLq/1XsGevVlKowf1cFhq5cIKLUVNt9XTEx5++Q=";
    };
  };
  dict2xml = {
    pname = "dict2xml";
    version = "release-1.7.7";
    src = fetchFromGitHub {
      owner = "delfick";
      repo = "python-dict2xml";
      rev = "release-1.7.7";
      fetchSubmodules = false;
      sha256 = "sha256-66ODdslXF6nWYqJku8cNG0RPK/YGEfbpHwVLLnSoDrk=";
    };
  };
  dutis = {
    pname = "dutis";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "tsonglew";
      repo = "dutis";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-YmkmHsA5PvAOowl9y7W8DB4wwdupKCxnQA1cuWxsiE8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-YmkmHsA5PvAOowl9y7W8DB4wwdupKCxnQA1cuWxsiE8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  "emacs29.no-frame-refocus-cocoa" = {
    pname = "emacs29.no-frame-refocus-cocoa";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-28/no-frame-refocus-cocoa.patch";
      sha256 = "sha256-+1d33IkKoHNJ8UOuZcK89D7a1v6/1WSwGiI1xaFfyr0=";
    };
    date = "2025-10-05";
  };
  "emacs29.role-patch" = {
    pname = "emacs29.role-patch";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2025-10-05";
  };
  "emacs29.round-undecorated-frame" = {
    pname = "emacs29.round-undecorated-frame";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-29/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2025-10-05";
  };
  "emacs29.system-appearance" = {
    pname = "emacs29.system-appearance";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-28/system-appearance.patch";
      sha256 = "sha256-1u4VmDmzi2r1Ode5vf8jEmPkUcH9Qu7A0SUxjJ24zZI=";
    };
    date = "2025-10-05";
  };
  "emacs30.ns-mac-input-source" = {
    pname = "emacs30.ns-mac-input-source";
    version = "934b6587b8261bffcfa8dfd1cac121a90f144a9b";
    src = fetchurl {
      url = "https://github.com/LuciusChen/.emacs.d/raw/934b6587b8261bffcfa8dfd1cac121a90f144a9b/patches/emacs-30/ns-alpha-background.patch";
      sha256 = "sha256-izzfjAWg4e8yYDuODXKIgwG7TdQUg2Su6ZebyzCg9hM=";
    };
    date = "2025-10-13";
  };
  "emacs30.role-patch" = {
    pname = "emacs30.role-patch";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2025-10-05";
  };
  "emacs30.round-undecorated-frame" = {
    pname = "emacs30.round-undecorated-frame";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-30/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2025-10-05";
  };
  "emacs30.system-appearance" = {
    pname = "emacs30.system-appearance";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-30/system-appearance.patch";
      sha256 = "sha256-nrPOgGQAJb/5brrrWJNDARY2jWNJ9OsMtO+LPVhHfbY=";
    };
    date = "2025-10-05";
  };
  "emacs31.ns-mac-input-source" = {
    pname = "emacs31.ns-mac-input-source";
    version = "934b6587b8261bffcfa8dfd1cac121a90f144a9b";
    src = fetchurl {
      url = "https://github.com/LuciusChen/.emacs.d/raw/934b6587b8261bffcfa8dfd1cac121a90f144a9b/patches/emacs-31/ns-mac-input-source.patch";
      sha256 = "sha256-mf77qesHJXQ6kBzZXg3rV1GT4dJYCUy1bMusN62g/6I=";
    };
    date = "2025-10-13";
  };
  "emacs31.round-undecorated-frame" = {
    pname = "emacs31.round-undecorated-frame";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-31/round-undecorated-frame.patch";
      sha256 = "sha256-JpR7ZyT8KfrdRIiYCMXPC0zmJ4zwT0YIaiHfUMjEFR0=";
    };
    date = "2025-10-05";
  };
  "emacs31.system-appearance" = {
    pname = "emacs31.system-appearance";
    version = "158df2e4f970e60ab9b3514a4ec64bf9dc985fcf";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/158df2e4f970e60ab9b3514a4ec64bf9dc985fcf/patches/emacs-31/system-appearance.patch";
      sha256 = "sha256-Uyg1A9te0oh+nXM7qq+A8sgQ5mjngumIvaWFWgsevrQ=";
    };
    date = "2025-10-05";
  };
  emacsclient = {
    pname = "emacsclient";
    version = "917f2f2694019d534098f5e2e365b5f6e5ddbd37";
    src = fetchurl {
      url = "https://github.com/nashamri/spacemacs-logo/raw/917f2f2694019d534098f5e2e365b5f6e5ddbd37/spacemacs.icns";
      sha256 = "sha256-s9uLfPpLxbziS8TcHt47dSxxhse1TAmZTqtexOqkiQA=";
    };
    date = "2018-08-26";
  };
  fav = {
    pname = "fav";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "kingwingfly";
      repo = "fav";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-UWhYI38+jYdazgfWpbAEJ8EjKvdCQFbCbYLaGWxC9OE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-UWhYI38+jYdazgfWpbAEJ8EjKvdCQFbCbYLaGWxC9OE=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  fisher = {
    pname = "fisher";
    version = "4.4.5";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "fisher";
      rev = "4.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-VC8LMjwIvF6oG8ZVtFQvo2mGdyAzQyluAGBoK8N2/QM=";
    };
  };
  flexfox = {
    pname = "flexfox";
    version = "v5.5.1";
    src = fetchFromGitHub {
      owner = "yuuqilin";
      repo = "FlexFox";
      rev = "v5.5.1";
      fetchSubmodules = false;
      sha256 = "sha256-fssoKXbyTCksxpb5Lirj6STbAJTQBuaKoKhGSXg77V4=";
    };
  };
  go-musicfox = {
    pname = "go-musicfox";
    version = "v4.7.1";
    src = fetchFromGitHub {
      owner = "go-musicfox";
      repo = "go-musicfox";
      rev = "v4.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-jrrxG26OKOUiUzv12Td8Vy12gnj9+mHog/vZSaTwqmw=";
    };
  };
  httpx = {
    pname = "httpx";
    version = "0.28.1";
    src = fetchFromGitHub {
      owner = "encode";
      repo = "httpx";
      rev = "0.28.1";
      fetchSubmodules = false;
      sha256 = "sha256-tB8uZm0kPRnmeOvsDdrkrHcMVIYfGanB4l/xHsTKpgE=";
    };
  };
  jeejah = {
    pname = "jeejah";
    version = "1555350e1e5eb77625334db1fba3c79b8c2c30a2";
    src = fetchgit {
      url = "https://gitlab.com/technomancy/jeejah";
      rev = "1555350e1e5eb77625334db1fba3c79b8c2c30a2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DyJJprTj9WjnhCC5CqudObLuae43zJD0VY9svGbqz10=";
    };
    date = "2023-09-28";
  };
  jeejah-rock = {
    pname = "jeejah-rock";
    version = "0.3.2-1";
    src = fetchurl {
      url = "https://luarocks.org/manifests/technomancy/jeejah-0.3.2-1.rockspec";
      sha256 = "sha256-Ouj+umHFOLtGwwMKochvG1fqIyRMdPzXg9039jD/bPk=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.32";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.32";
      fetchSubmodules = false;
      sha256 = "sha256-g8zZZ/uQeoJQIzpQY3oMUuWMu4/8OnaOLeLvaii+Tmk=";
    };
  };
  mac-app-util = {
    pname = "mac-app-util";
    version = "8414fa1e2cb775b17793104a9095aabeeada63ef";
    src = fetchurl {
      url = "https://github.com/hraban/mac-app-util/raw/8414fa1e2cb775b17793104a9095aabeeada63ef/main.lisp";
      sha256 = "sha256-mDFxuZN2y3+FcMWh3YdmC0ZjjRfZxD7K6QbqX8BzkWI=";
    };
    date = "2025-08-24";
  };
  manix = {
    pname = "manix";
    version = "5a69f920f1501f3f7e71a275ab8dbfd4a9f85fb3";
    src = fetchFromGitHub {
      owner = "kaii-zen";
      repo = "manix";
      rev = "5a69f920f1501f3f7e71a275ab8dbfd4a9f85fb3";
      fetchSubmodules = false;
      sha256 = "sha256-Qxs6p+MyS/0NTbJzLKvZHgKBUE1+z+zaINouG//Uio8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Qxs6p+MyS_0NTbJzLKvZHgKBUE1+z+zaINouG__Uio8=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2021-07-28";
  };
  mkalias = {
    pname = "mkalias";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "reckenrode";
      repo = "mkAlias";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-tL3C/b2BPOGQpV287wECDCDWmKwwPvezAAN3qz7N07M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-tL3C_b2BPOGQpV287wECDCDWmKwwPvezAAN3qz7N07M=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  musicdl = {
    pname = "musicdl";
    version = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "musicdl";
      rev = "ae213b2e5867fa12a6fa2789e24ea792aab38540";
      fetchSubmodules = false;
      sha256 = "sha256-AoMtlyRiceDzNXKz1K/EH5+/yU2B+UlEso5kjL5ojlI=";
    };
    date = "2023-02-22";
  };
  musicn = {
    pname = "musicn";
    version = "v1.5.3-beta.0";
    src = fetchFromGitHub {
      owner = "zonemeen";
      repo = "musicn";
      rev = "v1.5.3-beta.0";
      fetchSubmodules = false;
      sha256 = "sha256-loIT6Oy0TmkqtjEUMOVZEk27hr5wWPiP5WycGDXmo3s=";
    };
  };
  nowplaying-cli = {
    pname = "nowplaying-cli";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "kirtan-shah";
      repo = "nowplaying-cli";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-FkyrtgsGzpK2rLNr+oxfPUbX43TVXYeiBg7CN1JUg8Y=";
    };
  };
  pngpaste = {
    pname = "pngpaste";
    version = "0.2.3";
    src = fetchFromGitHub {
      owner = "jcsalterego";
      repo = "pngpaste";
      rev = "0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-uvajxSelk1Wfd5is5kmT2fzDShlufBgC0PDCeabEOSE=";
    };
  };
  pragmasevka = {
    pname = "pragmasevka";
    version = "33.3.1";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.1/pragma-sevka-mono.zip";
      sha256 = "sha256-jb3oXV2MjHfhSzxNc9GQBDQjfVgczs20tpHKy2PKn1c=";
    };
  };
  pragmasevka-nerd = {
    pname = "pragmasevka-nerd";
    version = "33.3.1";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.1/pragma-sevka-mono-nerd.zip";
      sha256 = "sha256-fYInFJfvquCa6/AaX4vOlFhETacbiVi2pPPYsqtoDrE=";
    };
  };
  pragmasevka-sans = {
    pname = "pragmasevka-sans";
    version = "33.3.1";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.1/pragma-sevka-sans.zip";
      sha256 = "sha256-NZMnssJzJpSCivRfdPzIzfxzpqhaz9UYK/jIkAYwZ0g=";
    };
  };
  pragmasevka-sc = {
    pname = "pragmasevka-sc";
    version = "33.3.1";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.1/Pragma-Sevka-SC.ttf";
      sha256 = "sha256-X9nf+p0qaJ9F2cF3RnttBQnmhOKDvorVwb1gM4AWtZY=";
    };
  };
  pragmasevka-sc-nf = {
    pname = "pragmasevka-sc-nf";
    version = "33.3.1";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.1/Pragma-Sevka-SC-NF.ttf";
      sha256 = "sha256-wObbvwFACjIyQgfODEMFg6GF6Fs8ecl01IbzIFdRBhc=";
    };
  };
  pragmasevka-serif = {
    pname = "pragmasevka-serif";
    version = "33.3.1";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.1/pragma-sevka-serif.zip";
      sha256 = "sha256-B7NY0e8cjLFKsGdAvjHTajg4KIi7k1unmylP93qDkes=";
    };
  };
  qbittorrent = {
    pname = "qbittorrent";
    version = "release-5.1.2.10";
    src = fetchFromGitHub {
      owner = "c0re100";
      repo = "qBittorrent-Enhanced-Edition";
      rev = "release-5.1.2.10";
      fetchSubmodules = false;
      sha256 = "sha256-Q3gipRgZCzihKUQZZmETT65AUSEUfgj9dFxZFybq258=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "11fa56f4f4568198ab40847b2ec470bde91c864b";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "11fa56f4f4568198ab40847b2ec470bde91c864b";
      fetchSubmodules = false;
      sha256 = "sha256-bZ4ojoC2uL8MR5IO7TaAkwQKplRU/poAaHouY5Ruq5Q=";
    };
    date = "2025-10-06";
  };
  sarasa-term = {
    pname = "sarasa-term";
    version = "2.3.1";
    src = fetchurl {
      url = "https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.3.1/SarasaTermSCNerd.ttc.tar.gz";
      sha256 = "sha256-WiXDbXdpRmf4R8IkdeIC3jUuwRKPUFUIHT6CzYoDmuI=";
    };
  };
  sd = {
    pname = "sd";
    version = "c730f8ad66a433ce7c9da954a77e81cca79bdce0";
    src = fetchFromGitHub {
      owner = "shanyouli";
      repo = "sd";
      rev = "c730f8ad66a433ce7c9da954a77e81cca79bdce0";
      fetchSubmodules = false;
      sha256 = "sha256-azFuxM/BFrDyTb3BlL119N77RRLTIXhcftl91iHcoyE=";
    };
    date = "2025-09-13";
  };
  seam = {
    pname = "seam";
    version = "v_cli.0.1.39";
    src = fetchFromGitHub {
      owner = "Borber";
      repo = "seam";
      rev = "v_cli.0.1.39";
      fetchSubmodules = false;
      sha256 = "sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0/P6SqHwxxvky8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0_P6SqHwxxvky8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  sidebery = {
    pname = "sidebery";
    version = "v5.3.3";
    src = fetchFromGitHub {
      owner = "mbnuqw";
      repo = "sidebery";
      rev = "v5.3.3";
      fetchSubmodules = false;
      sha256 = "sha256-wJqEuThoU5s5tYI3bpCBF5ADbLv8qeG3dDbOdL6eDoA=";
    };
  };
  singboxp = {
    pname = "singboxp";
    version = "2dcb86941f5db01bbe296acae555a3b1f38c0441";
    src = fetchFromGitHub {
      owner = "PuerNya";
      repo = "sing-box";
      rev = "2dcb86941f5db01bbe296acae555a3b1f38c0441";
      fetchSubmodules = false;
      sha256 = "sha256-pDwGJZYxhKdjMWl4DB4zcPJKL8qDqbXnJeHjmBhB7rY=";
    };
    date = "2025-08-04";
  };
  switchaudio-osx = {
    pname = "switchaudio-osx";
    version = "1.2.2";
    src = fetchFromGitHub {
      owner = "deweller";
      repo = "switchaudio-osx";
      rev = "1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-AZJn5kHK/al94ONfIHcG+W0jyMfgdJkIngN+PVj+I44=";
    };
  };
  tmux-fastcopy = {
    pname = "tmux-fastcopy";
    version = "v0.14.1";
    src = fetchFromGitHub {
      owner = "abhinav";
      repo = "tmux-fastcopy";
      rev = "v0.14.1";
      fetchSubmodules = false;
      sha256 = "sha256-j7Kk5uaC3vx4JifaAHXfLvXx6ask9YqlNKEiU5BYi+A=";
    };
  };
  userChromeJS = {
    pname = "userChromeJS";
    version = "b93a33da86c73020c286b01940556e923c994c4c";
    src = fetchFromGitHub {
      owner = "benzBrake";
      repo = "userChrome.js-Loader";
      rev = "b93a33da86c73020c286b01940556e923c994c4c";
      fetchSubmodules = false;
      sha256 = "sha256-ojJq1sYs4nZCYDQUckW7s6TeDpY7H8F6klj6iSVk2OA=";
    };
    date = "2025-09-02";
  };
  websocket-bridge-python = {
    pname = "websocket-bridge-python";
    version = "0.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/websocket_bridge_python/websocket_bridge_python-0.0.2.tar.gz";
      sha256 = "sha256-J9HGD3PSavZQwh2eZPbM6isdknZ1M2nkL5WHlYjRju8=";
    };
  };
  yabai-zsh-completions = {
    pname = "yabai-zsh-completions";
    version = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
    src = fetchFromGitHub {
      owner = "Amar1729";
      repo = "yabai-zsh-completions";
      rev = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
      fetchSubmodules = false;
      sha256 = "sha256-II00E32Pnt7PO+PcTtWp4NzSUDhQJTgAPw9HdlItbhQ=";
    };
    date = "2023-11-13";
  };
  zeroomega = {
    pname = "zeroomega";
    version = "3.4.1";
    src = fetchurl {
      url = "https://github.com/zero-peak/ZeroOmega/releases/download/3.4.1/zeroomega-3.4.1.xpi";
      sha256 = "sha256-AvKH8fqXObTpNPeXNerVySqJIAoteQhQCwRnjgZpnJI=";
    };
  };
  zpmod = {
    pname = "zpmod";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "z-shell";
      repo = "zpmod";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-vCQOn+8l9DcVJ6XbtHhr7N5IDr2Ht/JRub217ZO96Ok=";
    };
  };
}
