# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  alive-progress = {
    pname = "alive-progress";
    version = "3.3.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/alive-progress/alive-progress-3.3.0.tar.gz";
      sha256 = "sha256-RX3SQotI2s1JhUAipGRI0jakjxtyd4dAccOTlTB+gww=";
    };
  };
  antifennel = {
    pname = "antifennel";
    version = "cea2f62b71c53eeb2bfe056625a87f1a9ddfcddf";
    src = fetchgit {
      url = "https://git.sr.ht/~technomancy/antifennel";
      rev = "cea2f62b71c53eeb2bfe056625a87f1a9ddfcddf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LPQLxq7WQHi6CXgdYy6FKz04efFT5p6xPwDx5qhAw50=";
    };
    date = "20251005";
  };
  bash-env-json = {
    pname = "bash-env-json";
    version = "0.7.0";
    src = fetchurl {
      url = "https://github.com/tesujimath/bash-env-json/raw/0.7.0/bash-env-json";
      sha256 = "sha256-6x8zErIYZuk3qWB807rNVbvH9ZLl8cGffJnKrt7DlSg=";
    };
  };
  borders = {
    pname = "borders";
    version = "v1.9.0";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "JankyBorders";
      rev = "v1.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-j4hdW7JXTmSrE4bwlOkUYxA32AD011za7dmItwwIvyg=";
    };
  };
  cc-switch = {
    pname = "cc-switch";
    version = "v5.5.0";
    src = fetchFromGitHub {
      owner = "SaladDay";
      repo = "cc-switch-cli";
      rev = "v5.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-i2/Fy41pp6Ym2jvnECbTuTeSjH8wawkhA4SLSgWYNto=";
    };
    cargoLock."./src-tauri/Cargo.lock" = {
      lockFile = ./. + "/sha256-i2_Fy41pp6Ym2jvnECbTuTeSjH8wawkhA4SLSgWYNto=/./src-tauri/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  clash2singbox = {
    pname = "clash2singbox";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "xmdhs";
      repo = "clash2singbox";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-I4Z3tSZ+pwBqi0i6pQCrgP6M5F23gfbgpdprDDHHcA0=";
    };
  };
  darkreader = {
    pname = "darkreader";
    version = "4.9.125";
    src = fetchurl {
      url = "https://github.com/darkreader/darkreader/releases/download/v4.9.125/darkreader-firefox.xpi";
      sha256 = "sha256-pK3jPs5nPCqozvkCs0uprkt3bX9NOKyZ5UkiwLUXSZo=";
    };
  };
  deeplx = {
    pname = "deeplx";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "OwO-Network";
      repo = "DeepLX";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-M51z7iXJmYSRc9bsVPsbhD3v8Fq8Gwg+CO37B18wRZo=";
    };
  };
  dict2xml = {
    pname = "dict2xml";
    version = "release-1.7.8";
    src = fetchFromGitHub {
      owner = "delfick";
      repo = "python-dict2xml";
      rev = "release-1.7.8";
      fetchSubmodules = false;
      sha256 = "sha256-wCspFcqn6uAvecxx4Agzg7N3ps82mg8ukmmGwhfgajk=";
    };
  };
  dutis = {
    pname = "dutis";
    version = "v2.3.1";
    src = fetchFromGitHub {
      owner = "tsonglew";
      repo = "dutis";
      rev = "v2.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-90BVsQdFCC+uqvd1EvY/t+242AmQuTalD5dSiA4n2aA=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-90BVsQdFCC+uqvd1EvY_t+242AmQuTalD5dSiA4n2aA=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  emacs-reader = {
    pname = "emacs-reader";
    version = "7792885f28e65d8b413c3aaefa8ad9d467c7bd5f";
    src = fetchgit {
      url = "https://codeberg.org/divyaranjan/emacs-reader";
      rev = "7792885f28e65d8b413c3aaefa8ad9d467c7bd5f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3jkbEUOXOlKIMTBihEUWgF9+nq7tnYWGO449H7XM9vQ=";
    };
    date = "20260514";
  };
  "emacs29.no-frame-refocus-cocoa" = {
    pname = "emacs29.no-frame-refocus-cocoa";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-28/no-frame-refocus-cocoa.patch";
      sha256 = "sha256-+1d33IkKoHNJ8UOuZcK89D7a1v6/1WSwGiI1xaFfyr0=";
    };
    date = "2026-05-19";
  };
  "emacs29.role-patch" = {
    pname = "emacs29.role-patch";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2026-05-19";
  };
  "emacs29.round-undecorated-frame" = {
    pname = "emacs29.round-undecorated-frame";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-29/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2026-05-19";
  };
  "emacs29.system-appearance" = {
    pname = "emacs29.system-appearance";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-28/system-appearance.patch";
      sha256 = "sha256-1u4VmDmzi2r1Ode5vf8jEmPkUcH9Qu7A0SUxjJ24zZI=";
    };
    date = "2026-05-19";
  };
  "emacs30.ns-mac-input-source" = {
    pname = "emacs30.ns-mac-input-source";
    version = "1be3e9f6610bed79c8066608c0a79695d50582eb";
    src = fetchurl {
      url = "https://github.com/LuciusChen/.emacs.d/raw/1be3e9f6610bed79c8066608c0a79695d50582eb/scripts/macos/patches/emacs-30/ns-alpha-background.patch";
      sha256 = "sha256-izzfjAWg4e8yYDuODXKIgwG7TdQUg2Su6ZebyzCg9hM=";
    };
    date = "2026-05-19";
  };
  "emacs30.role-patch" = {
    pname = "emacs30.role-patch";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2026-05-19";
  };
  "emacs30.round-undecorated-frame" = {
    pname = "emacs30.round-undecorated-frame";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-30/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2026-05-19";
  };
  "emacs30.system-appearance" = {
    pname = "emacs30.system-appearance";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-30/system-appearance.patch";
      sha256 = "sha256-nrPOgGQAJb/5brrrWJNDARY2jWNJ9OsMtO+LPVhHfbY=";
    };
    date = "2026-05-19";
  };
  "emacs31.ns-mac-input-source" = {
    pname = "emacs31.ns-mac-input-source";
    version = "1be3e9f6610bed79c8066608c0a79695d50582eb";
    src = fetchurl {
      url = "https://github.com/LuciusChen/.emacs.d/raw/1be3e9f6610bed79c8066608c0a79695d50582eb/scripts/macos/patches/emacs-31/ns-mac-input-source.patch";
      sha256 = "sha256-mf77qesHJXQ6kBzZXg3rV1GT4dJYCUy1bMusN62g/6I=";
    };
    date = "2026-05-19";
  };
  "emacs31.round-undecorated-frame" = {
    pname = "emacs31.round-undecorated-frame";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-31/round-undecorated-frame.patch";
      sha256 = "sha256-JpR7ZyT8KfrdRIiYCMXPC0zmJ4zwT0YIaiHfUMjEFR0=";
    };
    date = "2026-05-19";
  };
  "emacs31.system-appearance" = {
    pname = "emacs31.system-appearance";
    version = "6fcb2956674564ad02f1d15cebe0a2d18be57037";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/6fcb2956674564ad02f1d15cebe0a2d18be57037/patches/emacs-31/system-appearance.patch";
      sha256 = "sha256-Uyg1A9te0oh+nXM7qq+A8sgQ5mjngumIvaWFWgsevrQ=";
    };
    date = "2026-05-19";
  };
  emacsclient = {
    pname = "emacsclient";
    version = "917f2f2694019d534098f5e2e365b5f6e5ddbd37";
    src = fetchurl {
      url = "https://github.com/nashamri/spacemacs-logo/raw/917f2f2694019d534098f5e2e365b5f6e5ddbd37/spacemacs.icns";
      sha256 = "sha256-s9uLfPpLxbziS8TcHt47dSxxhse1TAmZTqtexOqkiQA=";
    };
    date = "2018-08-26";
  };
  emt = {
    pname = "emt";
    version = "b7f46fae280dba3269e9110f3cb61d2dd4fa67cc";
    src = fetchFromGitHub {
      owner = "roife";
      repo = "emt";
      rev = "b7f46fae280dba3269e9110f3cb61d2dd4fa67cc";
      fetchSubmodules = false;
      sha256 = "sha256-ewHZxytYw2NPkhF4zdl/fRSiBSN2jZAkdM4Ykb1x90Q=";
    };
    date = "20250102";
  };
  ewt-rs = {
    pname = "ewt-rs";
    version = "v0.5.0";
    src = fetchFromGitHub {
      owner = "Master-Hash";
      repo = "ewt-rs";
      rev = "v0.5.0";
      fetchSubmodules = false;
      sha256 = "sha256-i8886lu0KZpjfD35X0A7zitUSld+mCbz5uI7+nFvnZ4=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-i8886lu0KZpjfD35X0A7zitUSld+mCbz5uI7+nFvnZ4=/Cargo.lock";
      outputHashes = {
        "rust_icu_common-5.6.0" = "sha256-p0Xkz9kLPO46pd0W2fEQazRYku5AR3eCqaAQ4wN1gE0=";
      };
    };
  };
  fav = {
    pname = "fav";
    version = "v1.2.5";
    src = fetchFromGitHub {
      owner = "kingwingfly";
      repo = "fav";
      rev = "v1.2.5";
      fetchSubmodules = false;
      sha256 = "sha256-BiSzXwsVLo5MrLeMm/2Rv/i7v9pDbYG30mp2jpcob/M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-BiSzXwsVLo5MrLeMm_2Rv_i7v9pDbYG30mp2jpcob_M=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  fisher = {
    pname = "fisher";
    version = "4.4.8";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "fisher";
      rev = "4.4.8";
      fetchSubmodules = false;
      sha256 = "sha256-Sf671UGOQXtOMrqoEOIBG5TCt0p5fd+aKGF2ExImbbs=";
    };
  };
  flexfox = {
    pname = "flexfox";
    version = "v6.0.7";
    src = fetchFromGitHub {
      owner = "yuuqilin";
      repo = "FlexFox";
      rev = "v6.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-N7lg9aUwGdVWoqa7zU0tiXAIdVHr6BqXTQCtfnC7IAQ=";
    };
  };
  go-musicfox = {
    pname = "go-musicfox";
    version = "v4.8.5";
    src = fetchFromGitHub {
      owner = "go-musicfox";
      repo = "go-musicfox";
      rev = "v4.8.5";
      fetchSubmodules = false;
      sha256 = "sha256-fgzj1L/oIVMCfiWaB83e9GEMyn6lfFSzF/hqq+i+5I0=";
    };
  };
  httpx = {
    pname = "httpx";
    version = "0.28.1";
    src = fetchFromGitHub {
      owner = "encode";
      repo = "httpx";
      rev = "0.28.1";
      fetchSubmodules = false;
      sha256 = "sha256-tB8uZm0kPRnmeOvsDdrkrHcMVIYfGanB4l/xHsTKpgE=";
    };
  };
  jcode = {
    pname = "jcode";
    version = "v0.12.3";
    src = fetchFromGitHub {
      owner = "1jehuang";
      repo = "jcode";
      rev = "v0.12.3";
      fetchSubmodules = false;
      sha256 = "sha256-ZuBVChtHxAFnLax/bgI/5OilPRKO5MJ3UTKNT/3CCIg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-ZuBVChtHxAFnLax_bgI_5OilPRKO5MJ3UTKNT_3CCIg=/Cargo.lock";
      outputHashes = {
        "agentgrep-0.1.2" = "sha256-Sf3EmWIZJ29KdaNbYRvM1tFXAPhOGhmpHOyqViEwkRI=";
        "mermaid-rs-renderer-0.2.0" = "sha256-lQCloOhTqqEU8MNrkUmmJFdoOTEE3j5nvZJo21GJlMU=";
      };
    };
  };
  jeejah = {
    pname = "jeejah";
    version = "c9c45fb4844035ffa71f33d8a571a532a6a82fd7";
    src = fetchgit {
      url = "https://gitlab.com/technomancy/jeejah";
      rev = "c9c45fb4844035ffa71f33d8a571a532a6a82fd7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qNmLqHfHY1ksMpGFmIHQpzS3QKG81CGSnM79GaqZRFE=";
    };
    date = "20251116";
  };
  jeejah-rock = {
    pname = "jeejah-rock";
    version = "0.3.2-1";
    src = fetchurl {
      url = "https://luarocks.org/manifests/technomancy/jeejah-0.3.2-1.rockspec";
      sha256 = "sha256-Ouj+umHFOLtGwwMKochvG1fqIyRMdPzXg9039jD/bPk=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.32";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.32";
      fetchSubmodules = false;
      sha256 = "sha256-g8zZZ/uQeoJQIzpQY3oMUuWMu4/8OnaOLeLvaii+Tmk=";
    };
  };
  mac-app-util = {
    pname = "mac-app-util";
    version = "4747968574ea58512c5385466400b2364c85d2d0";
    src = fetchurl {
      url = "https://github.com/hraban/mac-app-util/raw/4747968574ea58512c5385466400b2364c85d2d0/main.lisp";
      sha256 = "sha256-mDFxuZN2y3+FcMWh3YdmC0ZjjRfZxD7K6QbqX8BzkWI=";
    };
    date = "2025-12-26";
  };
  manix = {
    pname = "manix";
    version = "5a69f920f1501f3f7e71a275ab8dbfd4a9f85fb3";
    src = fetchFromGitHub {
      owner = "kaii-zen";
      repo = "manix";
      rev = "5a69f920f1501f3f7e71a275ab8dbfd4a9f85fb3";
      fetchSubmodules = false;
      sha256 = "sha256-Qxs6p+MyS/0NTbJzLKvZHgKBUE1+z+zaINouG//Uio8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Qxs6p+MyS_0NTbJzLKvZHgKBUE1+z+zaINouG__Uio8=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "20210728";
  };
  mkalias = {
    pname = "mkalias";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "reckenrode";
      repo = "mkAlias";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-YUvxBEwXu1LSYC+7g6inBizqgdjKnLugUTXtpSfayxI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-YUvxBEwXu1LSYC+7g6inBizqgdjKnLugUTXtpSfayxI=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  "mtranserver.linux.amd64" = {
    pname = "mtranserver.linux.amd64";
    version = "4.0.33";
    src = fetchurl {
      url = "https://github.com/xxnuo/MTranServer/releases/download/v4.0.33/mtranserver-4.0.33-linux-amd64";
      sha256 = "sha256-nVbDsdMckZOAUO51D39LqO96oXiHLXGcGYm+SAXPu5U=";
    };
  };
  "mtranserver.linux.arm64" = {
    pname = "mtranserver.linux.arm64";
    version = "4.0.33";
    src = fetchurl {
      url = "https://github.com/xxnuo/MTranServer/releases/download/v4.0.33/mtranserver-4.0.33-linux-arm64";
      sha256 = "sha256-Yrbkhjj1Akvp4MPSB5gU7wU2LBVms47sOnBrggY8Pys=";
    };
  };
  "mtranserver.mac.amd64" = {
    pname = "mtranserver.mac.amd64";
    version = "4.0.33";
    src = fetchurl {
      url = "https://github.com/xxnuo/MTranServer/releases/download/v4.0.33/mtranserver-4.0.33-darwin-amd64";
      sha256 = "sha256-jfwUg3V1I3fpzMZFn6DYGducPoc6ote0eKUk7f9LIDw=";
    };
  };
  "mtranserver.mac.arm64" = {
    pname = "mtranserver.mac.arm64";
    version = "4.0.33";
    src = fetchurl {
      url = "https://github.com/xxnuo/MTranServer/releases/download/v4.0.33/mtranserver-4.0.33-darwin-arm64";
      sha256 = "sha256-yvUbTXKiAcAV0tydsAYi4abHDpE1c3udiq4WSRvLqP8=";
    };
  };
  musicdl = {
    pname = "musicdl";
    version = "be5c81b05d978cfd9149adeaa5ec79ba3edb4f24";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "musicdl";
      rev = "be5c81b05d978cfd9149adeaa5ec79ba3edb4f24";
      fetchSubmodules = false;
      sha256 = "sha256-/M1o8770VotI+2YHi0idMN9LdwQLmLS1ucxo/fpndOo=";
    };
    date = "20260519";
  };
  musicn = {
    pname = "musicn";
    version = "v1.5.3-beta.0";
    src = fetchFromGitHub {
      owner = "zonemeen";
      repo = "musicn";
      rev = "v1.5.3-beta.0";
      fetchSubmodules = false;
      sha256 = "sha256-loIT6Oy0TmkqtjEUMOVZEk27hr5wWPiP5WycGDXmo3s=";
    };
  };
  nowplaying-cli = {
    pname = "nowplaying-cli";
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "kirtan-shah";
      repo = "nowplaying-cli";
      rev = "v2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-jPW3WEq1ZhxBojMO+5WF8ohO1rLmlAJKGdh1HfSOR5s=";
    };
  };
  nu-lint = {
    pname = "nu-lint";
    version = "ed6c21c71cd2aaeb7711df86db6399b077517025";
    src = fetchFromGitHub {
      owner = "wvhulle";
      repo = "nu-lint";
      rev = "ed6c21c71cd2aaeb7711df86db6399b077517025";
      fetchSubmodules = false;
      sha256 = "sha256-zALlwEEzk6IapnLbqn9v/HV5QC9dvJi7VzEWgCQJT2s=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-zALlwEEzk6IapnLbqn9v_HV5QC9dvJi7VzEWgCQJT2s=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "20260502";
  };
  openwith = {
    pname = "openwith";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "ColeMei";
      repo = "openwith";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-UY60cap16AMvsw+cYm2sNKk/l+XIftyvKGTsKwDdaLM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-UY60cap16AMvsw+cYm2sNKk_l+XIftyvKGTsKwDdaLM=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  pngpaste = {
    pname = "pngpaste";
    version = "0.2.3";
    src = fetchFromGitHub {
      owner = "jcsalterego";
      repo = "pngpaste";
      rev = "0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-uvajxSelk1Wfd5is5kmT2fzDShlufBgC0PDCeabEOSE=";
    };
  };
  pragmasevka = {
    pname = "pragmasevka";
    version = "34.5.0";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v34.5.0/pragma-sevka-mono.zip";
      sha256 = "sha256-Z5vVsiWd4xwNJT1uuRfYzphRHEQ6kxFCz1iNgI4fOjI=";
    };
  };
  pragmasevka-nerd = {
    pname = "pragmasevka-nerd";
    version = "34.5.0";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v34.5.0/pragma-sevka-mono-nerd.zip";
      sha256 = "sha256-Cq9KuO7pA5vB0iCpw1nSgooo46YFR4ZfenNLr9qZ8ts=";
    };
  };
  pragmasevka-sans = {
    pname = "pragmasevka-sans";
    version = "34.5.0";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v34.5.0/pragma-sevka-sans.zip";
      sha256 = "sha256-O4Q3b7iTNcNLQF4w3XQngGswD8xrChpLAkwdjhZHE9I=";
    };
  };
  pragmasevka-sc = {
    pname = "pragmasevka-sc";
    version = "34.5.0";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v34.5.0/Pragma-Sevka-SC-Regular.ttf";
      sha256 = "sha256-V9wkjJ0zwkHWvef5CY1lLsSyLjeRha/n+wSGg+URQaM=";
    };
  };
  pragmasevka-sc-nf = {
    pname = "pragmasevka-sc-nf";
    version = "34.5.0";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v34.5.0/Pragma-Sevka-SC-NF-Regular.ttf";
      sha256 = "sha256-cTBB+mkfyGYxUlGR5RJxDj3GpXCvg9mezAQwubRwjFc=";
    };
  };
  pragmasevka-serif = {
    pname = "pragmasevka-serif";
    version = "34.5.0";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v34.5.0/pragma-sevka-serif.zip";
      sha256 = "sha256-2aQK5+xwnSTmyEYWbLuYaZ9qzd9eYvMmjUqyEq8cnXQ=";
    };
  };
  pyfreeproxy = {
    pname = "pyfreeproxy";
    version = "7902efbf5138bf7e613f0c9b7615fe4bbb26b869";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "freeproxy";
      rev = "7902efbf5138bf7e613f0c9b7615fe4bbb26b869";
      fetchSubmodules = false;
      sha256 = "sha256-rQMYF6RcspSXwX3EGOhegAtvRO7F7NTrEFs76jeBtQM=";
    };
    date = "20260519";
  };
  rime-frost = {
    pname = "rime-frost";
    version = "1.0.4";
    src = fetchFromGitHub {
      owner = "gaboolic";
      repo = "rime-frost";
      rev = "1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-1yxbLuVcCqgHGS14AecbVL7AQFGC/wbFO7US3Onz/R0=";
    };
  };
  rime-ice = {
    pname = "rime-ice";
    version = "a5d123bcb5d3f259560c262bd6e1fb64bfd92fb3";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "a5d123bcb5d3f259560c262bd6e1fb64bfd92fb3";
      fetchSubmodules = false;
      sha256 = "sha256-z/5Vf/i4IdkxNUObOhfW4T7wP0fICmSCgpKu2E2zI1M=";
    };
    date = "20260518";
  };
  sarasa-term = {
    pname = "sarasa-term";
    version = "2.3.1";
    src = fetchurl {
      url = "https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.3.1/SarasaTermSCNerd.ttc.tar.gz";
      sha256 = "sha256-WiXDbXdpRmf4R8IkdeIC3jUuwRKPUFUIHT6CzYoDmuI=";
    };
  };
  sd = {
    pname = "sd";
    version = "748570a6877b028969b16707d32e8dfa58ee49c8";
    src = fetchFromGitHub {
      owner = "shanyouli";
      repo = "sd";
      rev = "748570a6877b028969b16707d32e8dfa58ee49c8";
      fetchSubmodules = false;
      sha256 = "sha256-wl/xsew2WkEMny2u8rSbKPafjwuGg8uRQKnH4ZjnAnY=";
    };
    date = "20260421";
  };
  seam = {
    pname = "seam";
    version = "v_cli.0.1.39";
    src = fetchFromGitHub {
      owner = "Borber";
      repo = "seam";
      rev = "v_cli.0.1.39";
      fetchSubmodules = false;
      sha256 = "sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0/P6SqHwxxvky8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0_P6SqHwxxvky8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  sidebery = {
    pname = "sidebery";
    version = "v5.5.2";
    src = fetchFromGitHub {
      owner = "mbnuqw";
      repo = "sidebery";
      rev = "v5.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-V77H6DfLW1Xy3kdjtCSTptfagxo0A6Syv+c3Zm3fJvc=";
    };
  };
  singboxp = {
    pname = "singboxp";
    version = "1bd617e1afff7faa51515cb8a74b63042009f555";
    src = fetchFromGitHub {
      owner = "PuerNya";
      repo = "sing-box";
      rev = "1bd617e1afff7faa51515cb8a74b63042009f555";
      fetchSubmodules = false;
      sha256 = "sha256-KpXyy/eng8dmLvpdMyFnNoBvID0ejIytM4p7WyM08zs=";
    };
    date = "20260112";
  };
  switchaudio-osx = {
    pname = "switchaudio-osx";
    version = "1.2.2";
    src = fetchFromGitHub {
      owner = "deweller";
      repo = "switchaudio-osx";
      rev = "1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-AZJn5kHK/al94ONfIHcG+W0jyMfgdJkIngN+PVj+I44=";
    };
  };
  tmux-fastcopy = {
    pname = "tmux-fastcopy";
    version = "v0.14.1";
    src = fetchFromGitHub {
      owner = "abhinav";
      repo = "tmux-fastcopy";
      rev = "v0.14.1";
      fetchSubmodules = false;
      sha256 = "sha256-j7Kk5uaC3vx4JifaAHXfLvXx6ask9YqlNKEiU5BYi+A=";
    };
  };
  userChromeJS = {
    pname = "userChromeJS";
    version = "e377756420009e3c04e78642dd00d5e8d7c06690";
    src = fetchFromGitHub {
      owner = "benzBrake";
      repo = "userChrome.js-Loader";
      rev = "e377756420009e3c04e78642dd00d5e8d7c06690";
      fetchSubmodules = false;
      sha256 = "sha256-4NLEl+zx9cZz8htAOTW4WyT6DWNH04qZ1Lj5BVJWDVw=";
    };
    date = "20260407";
  };
  websocket-bridge-python = {
    pname = "websocket-bridge-python";
    version = "0.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/websocket_bridge_python/websocket_bridge_python-0.0.2.tar.gz";
      sha256 = "sha256-J9HGD3PSavZQwh2eZPbM6isdknZ1M2nkL5WHlYjRju8=";
    };
  };
  yabai-zsh-completions = {
    pname = "yabai-zsh-completions";
    version = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
    src = fetchFromGitHub {
      owner = "Amar1729";
      repo = "yabai-zsh-completions";
      rev = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
      fetchSubmodules = false;
      sha256 = "sha256-II00E32Pnt7PO+PcTtWp4NzSUDhQJTgAPw9HdlItbhQ=";
    };
    date = "20231113";
  };
  zpmod = {
    pname = "zpmod";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "z-shell";
      repo = "zpmod";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-vCQOn+8l9DcVJ6XbtHhr7N5IDr2Ht/JRub217ZO96Ok=";
    };
  };
}
