# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aerospace = {
    pname = "aerospace";
    version = "0.20.0-Beta";
    src = fetchurl {
      url = "https://github.com/nikitabobko/AeroSpace/releases/download/v0.20.0-Beta/AeroSpace-v0.20.0-Beta.zip";
      sha256 = "sha256-j68D9BOKjApWSz62Sq2nPyChJol0j3uOj6LKJ3tQos4=";
    };
  };
  alive-progress = {
    pname = "alive-progress";
    version = "3.3.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/a/alive-progress/alive-progress-3.3.0.tar.gz";
      sha256 = "sha256-RX3SQotI2s1JhUAipGRI0jakjxtyd4dAccOTlTB+gww=";
    };
  };
  antifennel = {
    pname = "antifennel";
    version = "cea2f62b71c53eeb2bfe056625a87f1a9ddfcddf";
    src = fetchgit {
      url = "https://git.sr.ht/~technomancy/antifennel";
      rev = "cea2f62b71c53eeb2bfe056625a87f1a9ddfcddf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LPQLxq7WQHi6CXgdYy6FKz04efFT5p6xPwDx5qhAw50=";
    };
    date = "2025-10-05";
  };
  bash-env-json = {
    pname = "bash-env-json";
    version = "0.7.0";
    src = fetchurl {
      url = "https://github.com/tesujimath/bash-env-json/raw/0.7.0/bash-env-json";
      sha256 = "sha256-6x8zErIYZuk3qWB807rNVbvH9ZLl8cGffJnKrt7DlSg=";
    };
  };
  bbdown = {
    pname = "bbdown";
    version = "d869225aed7ccdb43e48277c6bd67c690d76f29e";
    src = fetchFromGitHub {
      owner = "nilaoda";
      repo = "BBDown";
      rev = "d869225aed7ccdb43e48277c6bd67c690d76f29e";
      fetchSubmodules = false;
      sha256 = "sha256-C84eQ3Y3/YHup1dx4BtH9qstRs3dgXMCAmZXemvG1Xc=";
    };
    date = "2025-10-23";
  };
  borders = {
    pname = "borders";
    version = "v1.8.4";
    src = fetchFromGitHub {
      owner = "FelixKratz";
      repo = "JankyBorders";
      rev = "v1.8.4";
      fetchSubmodules = false;
      sha256 = "sha256-31Er+cUQNJbZnXKC6KvlrBhOvyPAM7nP3BaxunAtvWg=";
    };
  };
  clash2singbox = {
    pname = "clash2singbox";
    version = "v0.1.4";
    src = fetchFromGitHub {
      owner = "xmdhs";
      repo = "clash2singbox";
      rev = "v0.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-qEv5lmuu4UWaxmCQ0sb21TMJVhYaW7VscD6O+dOWjgE=";
    };
  };
  darkreader = {
    pname = "darkreader";
    version = "4.9.118";
    src = fetchurl {
      url = "https://github.com/darkreader/darkreader/releases/download/v4.9.118/darkreader-firefox.xpi";
      sha256 = "sha256-AVmAWk/jCz32D+t8udvd9q8euhjw3+te6FcrzKucPFw=";
    };
  };
  deeplx = {
    pname = "deeplx";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "OwO-Network";
      repo = "DeepLX";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-LJC9iSH9XrX87hqhZVLgmSml7wLj6G0H6RE6kxKVyFg=";
    };
  };
  dict2xml = {
    pname = "dict2xml";
    version = "release-1.7.7";
    src = fetchFromGitHub {
      owner = "delfick";
      repo = "python-dict2xml";
      rev = "release-1.7.7";
      fetchSubmodules = false;
      sha256 = "sha256-66ODdslXF6nWYqJku8cNG0RPK/YGEfbpHwVLLnSoDrk=";
    };
  };
  dutis = {
    pname = "dutis";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "tsonglew";
      repo = "dutis";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-YmkmHsA5PvAOowl9y7W8DB4wwdupKCxnQA1cuWxsiE8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-YmkmHsA5PvAOowl9y7W8DB4wwdupKCxnQA1cuWxsiE8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  "emacs29.no-frame-refocus-cocoa" = {
    pname = "emacs29.no-frame-refocus-cocoa";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-28/no-frame-refocus-cocoa.patch";
      sha256 = "sha256-+1d33IkKoHNJ8UOuZcK89D7a1v6/1WSwGiI1xaFfyr0=";
    };
    date = "2025-12-30";
  };
  "emacs29.role-patch" = {
    pname = "emacs29.role-patch";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2025-12-30";
  };
  "emacs29.round-undecorated-frame" = {
    pname = "emacs29.round-undecorated-frame";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-29/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2025-12-30";
  };
  "emacs29.system-appearance" = {
    pname = "emacs29.system-appearance";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-28/system-appearance.patch";
      sha256 = "sha256-1u4VmDmzi2r1Ode5vf8jEmPkUcH9Qu7A0SUxjJ24zZI=";
    };
    date = "2025-12-30";
  };
  "emacs30.ns-mac-input-source" = {
    pname = "emacs30.ns-mac-input-source";
    version = "b4091c36b3f16f14fbdf5da5709f965301737999";
    src = fetchurl {
      url = "https://github.com/LuciusChen/.emacs.d/raw/b4091c36b3f16f14fbdf5da5709f965301737999/patches/emacs-30/ns-alpha-background.patch";
      sha256 = "sha256-izzfjAWg4e8yYDuODXKIgwG7TdQUg2Su6ZebyzCg9hM=";
    };
    date = "2025-12-23";
  };
  "emacs30.role-patch" = {
    pname = "emacs30.role-patch";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-28/fix-window-role.patch";
      sha256 = "sha256-H4Qj6n5uZsmsbdjjexGZctqhJk3gAXKiSnmnEO/LgTA=";
    };
    date = "2025-12-30";
  };
  "emacs30.round-undecorated-frame" = {
    pname = "emacs30.round-undecorated-frame";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-30/round-undecorated-frame.patch";
      sha256 = "sha256-dFH4D1WYQOVOagUuVdEQB3irxV+Y8dDAOKJOJXc/KHQ=";
    };
    date = "2025-12-30";
  };
  "emacs30.system-appearance" = {
    pname = "emacs30.system-appearance";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-30/system-appearance.patch";
      sha256 = "sha256-nrPOgGQAJb/5brrrWJNDARY2jWNJ9OsMtO+LPVhHfbY=";
    };
    date = "2025-12-30";
  };
  "emacs31.ns-mac-input-source" = {
    pname = "emacs31.ns-mac-input-source";
    version = "b4091c36b3f16f14fbdf5da5709f965301737999";
    src = fetchurl {
      url = "https://github.com/LuciusChen/.emacs.d/raw/b4091c36b3f16f14fbdf5da5709f965301737999/patches/emacs-31/ns-mac-input-source.patch";
      sha256 = "sha256-mf77qesHJXQ6kBzZXg3rV1GT4dJYCUy1bMusN62g/6I=";
    };
    date = "2025-12-23";
  };
  "emacs31.round-undecorated-frame" = {
    pname = "emacs31.round-undecorated-frame";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-31/round-undecorated-frame.patch";
      sha256 = "sha256-JpR7ZyT8KfrdRIiYCMXPC0zmJ4zwT0YIaiHfUMjEFR0=";
    };
    date = "2025-12-30";
  };
  "emacs31.system-appearance" = {
    pname = "emacs31.system-appearance";
    version = "a320ad7c765b49f7d846db82d7b4308e4b4c2024";
    src = fetchurl {
      url = "https://github.com/d12frosted/homebrew-emacs-plus/raw/a320ad7c765b49f7d846db82d7b4308e4b4c2024/patches/emacs-31/system-appearance.patch";
      sha256 = "sha256-Uyg1A9te0oh+nXM7qq+A8sgQ5mjngumIvaWFWgsevrQ=";
    };
    date = "2025-12-30";
  };
  emacsclient = {
    pname = "emacsclient";
    version = "917f2f2694019d534098f5e2e365b5f6e5ddbd37";
    src = fetchurl {
      url = "https://github.com/nashamri/spacemacs-logo/raw/917f2f2694019d534098f5e2e365b5f6e5ddbd37/spacemacs.icns";
      sha256 = "sha256-s9uLfPpLxbziS8TcHt47dSxxhse1TAmZTqtexOqkiQA=";
    };
    date = "2018-08-26";
  };
  fav = {
    pname = "fav";
    version = "v1.2.2";
    src = fetchFromGitHub {
      owner = "kingwingfly";
      repo = "fav";
      rev = "v1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-fN6X4q2mWKNUr6nEevCaY/Nd9Y8liJhffe3jhr6u+vg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-fN6X4q2mWKNUr6nEevCaY_Nd9Y8liJhffe3jhr6u+vg=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  fisher = {
    pname = "fisher";
    version = "4.4.5";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "fisher";
      rev = "4.4.5";
      fetchSubmodules = false;
      sha256 = "sha256-VC8LMjwIvF6oG8ZVtFQvo2mGdyAzQyluAGBoK8N2/QM=";
    };
  };
  flexfox = {
    pname = "flexfox";
    version = "v5.7.5";
    src = fetchFromGitHub {
      owner = "yuuqilin";
      repo = "FlexFox";
      rev = "v5.7.5";
      fetchSubmodules = false;
      sha256 = "sha256-kw0PrQLXWDnwHZpQMMFL1J0SoQYpNOumvyW8WRftCYU=";
    };
  };
  go-musicfox = {
    pname = "go-musicfox";
    version = "v4.7.2";
    src = fetchFromGitHub {
      owner = "go-musicfox";
      repo = "go-musicfox";
      rev = "v4.7.2";
      fetchSubmodules = false;
      sha256 = "sha256-RJPb+aZawU22HBXTfr7+TP0ocFsNrP1mOHvHPRm2RnA=";
    };
  };
  httpx = {
    pname = "httpx";
    version = "0.28.1";
    src = fetchFromGitHub {
      owner = "encode";
      repo = "httpx";
      rev = "0.28.1";
      fetchSubmodules = false;
      sha256 = "sha256-tB8uZm0kPRnmeOvsDdrkrHcMVIYfGanB4l/xHsTKpgE=";
    };
  };
  jeejah = {
    pname = "jeejah";
    version = "c9c45fb4844035ffa71f33d8a571a532a6a82fd7";
    src = fetchgit {
      url = "https://gitlab.com/technomancy/jeejah";
      rev = "c9c45fb4844035ffa71f33d8a571a532a6a82fd7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qNmLqHfHY1ksMpGFmIHQpzS3QKG81CGSnM79GaqZRFE=";
    };
    date = "2025-11-16";
  };
  jeejah-rock = {
    pname = "jeejah-rock";
    version = "0.3.2-1";
    src = fetchurl {
      url = "https://luarocks.org/manifests/technomancy/jeejah-0.3.2-1.rockspec";
      sha256 = "sha256-Ouj+umHFOLtGwwMKochvG1fqIyRMdPzXg9039jD/bPk=";
    };
  };
  lporg = {
    pname = "lporg";
    version = "v20.4.32";
    src = fetchFromGitHub {
      owner = "blacktop";
      repo = "lporg";
      rev = "v20.4.32";
      fetchSubmodules = false;
      sha256 = "sha256-g8zZZ/uQeoJQIzpQY3oMUuWMu4/8OnaOLeLvaii+Tmk=";
    };
  };
  mac-app-util = {
    pname = "mac-app-util";
    version = "4747968574ea58512c5385466400b2364c85d2d0";
    src = fetchurl {
      url = "https://github.com/hraban/mac-app-util/raw/4747968574ea58512c5385466400b2364c85d2d0/main.lisp";
      sha256 = "sha256-mDFxuZN2y3+FcMWh3YdmC0ZjjRfZxD7K6QbqX8BzkWI=";
    };
    date = "2025-12-26";
  };
  manix = {
    pname = "manix";
    version = "5a69f920f1501f3f7e71a275ab8dbfd4a9f85fb3";
    src = fetchFromGitHub {
      owner = "kaii-zen";
      repo = "manix";
      rev = "5a69f920f1501f3f7e71a275ab8dbfd4a9f85fb3";
      fetchSubmodules = false;
      sha256 = "sha256-Qxs6p+MyS/0NTbJzLKvZHgKBUE1+z+zaINouG//Uio8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Qxs6p+MyS_0NTbJzLKvZHgKBUE1+z+zaINouG__Uio8=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2021-07-28";
  };
  mkalias = {
    pname = "mkalias";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "reckenrode";
      repo = "mkAlias";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-tL3C/b2BPOGQpV287wECDCDWmKwwPvezAAN3qz7N07M=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-tL3C_b2BPOGQpV287wECDCDWmKwwPvezAAN3qz7N07M=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  mtranserver = {
    pname = "mtranserver";
    version = "v3.1.24";
    src = fetchFromGitHub {
      owner = "xxnuo";
      repo = "MTranServer";
      rev = "v3.1.24";
      fetchSubmodules = false;
      sha256 = "sha256-DpwkVAV31lsi44Kgr5XyuhJjsvX9gY4rrhvmKqaoEWY=";
    };
  };
  musicdl = {
    pname = "musicdl";
    version = "5aded36ce802d08ef268b7dd227cb967cb50fcaf";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "musicdl";
      rev = "5aded36ce802d08ef268b7dd227cb967cb50fcaf";
      fetchSubmodules = false;
      sha256 = "sha256-SQ9nCTWlETwXHMBAZnMI1Qdu/bx/qh7FTGocA+JX9Ko=";
    };
    date = "2025-12-30";
  };
  musicn = {
    pname = "musicn";
    version = "v1.5.3-beta.0";
    src = fetchFromGitHub {
      owner = "zonemeen";
      repo = "musicn";
      rev = "v1.5.3-beta.0";
      fetchSubmodules = false;
      sha256 = "sha256-loIT6Oy0TmkqtjEUMOVZEk27hr5wWPiP5WycGDXmo3s=";
    };
  };
  nowplaying-cli = {
    pname = "nowplaying-cli";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "kirtan-shah";
      repo = "nowplaying-cli";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-FkyrtgsGzpK2rLNr+oxfPUbX43TVXYeiBg7CN1JUg8Y=";
    };
  };
  nu-lint = {
    pname = "nu-lint";
    version = "873cc30cccbbc9766b717a7376c9b314d68a1aa2";
    src = fetchFromGitHub {
      owner = "wvhulle";
      repo = "nu-lint";
      rev = "873cc30cccbbc9766b717a7376c9b314d68a1aa2";
      fetchSubmodules = false;
      sha256 = "sha256-O7KnSjQCP7Xj67CJLMbzKQ+nD+Mo7XePIiOgZGvd140=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-O7KnSjQCP7Xj67CJLMbzKQ+nD+Mo7XePIiOgZGvd140=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2025-12-29";
  };
  pngpaste = {
    pname = "pngpaste";
    version = "0.2.3";
    src = fetchFromGitHub {
      owner = "jcsalterego";
      repo = "pngpaste";
      rev = "0.2.3";
      fetchSubmodules = false;
      sha256 = "sha256-uvajxSelk1Wfd5is5kmT2fzDShlufBgC0PDCeabEOSE=";
    };
  };
  pragmasevka = {
    pname = "pragmasevka";
    version = "33.3.6";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.6/pragma-sevka-mono.zip";
      sha256 = "sha256-YIuMi08Ybl1/WcCOeIy0wxX2LpmHbHAy0A3qNiZvmmI=";
    };
  };
  pragmasevka-nerd = {
    pname = "pragmasevka-nerd";
    version = "33.3.6";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.6/pragma-sevka-mono-nerd.zip";
      sha256 = "sha256-2a/yUc0+qF5yVVIdx+EJvgygaWqLUN8cwD9oB3a56tE=";
    };
  };
  pragmasevka-sans = {
    pname = "pragmasevka-sans";
    version = "33.3.6";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.6/pragma-sevka-sans.zip";
      sha256 = "sha256-LUZp2Gcc3igwMJrX+O+/UBAjS136J/EFeascWBdu0ac=";
    };
  };
  pragmasevka-sc = {
    pname = "pragmasevka-sc";
    version = "33.3.6";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.6/Pragma-Sevka-SC.ttf";
      sha256 = "sha256-n+deQ38Z6fmNi1lJFt38QjAO5dlnKvdIPb5eHMS5rMA=";
    };
  };
  pragmasevka-sc-nf = {
    pname = "pragmasevka-sc-nf";
    version = "33.3.6";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.6/Pragma-Sevka-SC-NF.ttf";
      sha256 = "sha256-1LjRuUDa7/LCEBkmRYBDkLnlgtukTv5NRnnmk+eFkY0=";
    };
  };
  pragmasevka-serif = {
    pname = "pragmasevka-serif";
    version = "33.3.6";
    src = fetchurl {
      url = "https://github.com/shanyouli/iosevka/releases/download/v33.3.6/pragma-sevka-serif.zip";
      sha256 = "sha256-R10JS0Se9kdGd/KrIVfNgFmrreaxbwQHq/jF30o2u+4=";
    };
  };
  pyfreeproxy = {
    pname = "pyfreeproxy";
    version = "34e433aee7aade226ccd1b6f31d0faa7d0d1580f";
    src = fetchFromGitHub {
      owner = "CharlesPikachu";
      repo = "freeproxy";
      rev = "34e433aee7aade226ccd1b6f31d0faa7d0d1580f";
      fetchSubmodules = false;
      sha256 = "sha256-rPQl9mLSdBujAEtUi9ED/8zxLdAi96GeRhLVMHdqNhA=";
    };
    date = "2025-12-30";
  };
  rime-ice = {
    pname = "rime-ice";
    version = "cc51682a850e9b89db8856c589b8c13f8b534a7c";
    src = fetchFromGitHub {
      owner = "iDvel";
      repo = "rime-ice";
      rev = "cc51682a850e9b89db8856c589b8c13f8b534a7c";
      fetchSubmodules = false;
      sha256 = "sha256-rEWf96uoYZm/n8IBSSG5qnXBgiWvrzhD1+GutLqMlg8=";
    };
    date = "2025-12-24";
  };
  sarasa-term = {
    pname = "sarasa-term";
    version = "2.3.1";
    src = fetchurl {
      url = "https://github.com/laishulu/Sarasa-Term-SC-Nerd/releases/download/v2.3.1/SarasaTermSCNerd.ttc.tar.gz";
      sha256 = "sha256-WiXDbXdpRmf4R8IkdeIC3jUuwRKPUFUIHT6CzYoDmuI=";
    };
  };
  sd = {
    pname = "sd";
    version = "c730f8ad66a433ce7c9da954a77e81cca79bdce0";
    src = fetchFromGitHub {
      owner = "shanyouli";
      repo = "sd";
      rev = "c730f8ad66a433ce7c9da954a77e81cca79bdce0";
      fetchSubmodules = false;
      sha256 = "sha256-azFuxM/BFrDyTb3BlL119N77RRLTIXhcftl91iHcoyE=";
    };
    date = "2025-09-13";
  };
  seam = {
    pname = "seam";
    version = "v_cli.0.1.39";
    src = fetchFromGitHub {
      owner = "Borber";
      repo = "seam";
      rev = "v_cli.0.1.39";
      fetchSubmodules = false;
      sha256 = "sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0/P6SqHwxxvky8=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-rWbswgVQNA006gi9G+Vma+y0NbMDC0_P6SqHwxxvky8=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  sidebery = {
    pname = "sidebery";
    version = "v5.4.0";
    src = fetchFromGitHub {
      owner = "mbnuqw";
      repo = "sidebery";
      rev = "v5.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-Y7Aq+fZPJcYQcJjykyobT5LFanz4TcMSNoJBWgr1w9Q=";
    };
  };
  singboxp = {
    pname = "singboxp";
    version = "daef974c320f05e57abae651eee1e9ca93220508";
    src = fetchFromGitHub {
      owner = "PuerNya";
      repo = "sing-box";
      rev = "daef974c320f05e57abae651eee1e9ca93220508";
      fetchSubmodules = false;
      sha256 = "sha256-itKsB+D+ahhNdw56pqCXpjknvJdnrd9IBaElG2MdhL4=";
    };
    date = "2025-12-17";
  };
  switchaudio-osx = {
    pname = "switchaudio-osx";
    version = "1.2.2";
    src = fetchFromGitHub {
      owner = "deweller";
      repo = "switchaudio-osx";
      rev = "1.2.2";
      fetchSubmodules = false;
      sha256 = "sha256-AZJn5kHK/al94ONfIHcG+W0jyMfgdJkIngN+PVj+I44=";
    };
  };
  tmux-fastcopy = {
    pname = "tmux-fastcopy";
    version = "v0.14.1";
    src = fetchFromGitHub {
      owner = "abhinav";
      repo = "tmux-fastcopy";
      rev = "v0.14.1";
      fetchSubmodules = false;
      sha256 = "sha256-j7Kk5uaC3vx4JifaAHXfLvXx6ask9YqlNKEiU5BYi+A=";
    };
  };
  userChromeJS = {
    pname = "userChromeJS";
    version = "3868c57a0941e856538380e6a612e41d5ed605e3";
    src = fetchFromGitHub {
      owner = "benzBrake";
      repo = "userChrome.js-Loader";
      rev = "3868c57a0941e856538380e6a612e41d5ed605e3";
      fetchSubmodules = false;
      sha256 = "sha256-d/T6qU1X8cpwSTdA81OI4ZQRM4NRszIRTFNnuYkOXHg=";
    };
    date = "2025-12-19";
  };
  websocket-bridge-python = {
    pname = "websocket-bridge-python";
    version = "0.0.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/websocket_bridge_python/websocket_bridge_python-0.0.2.tar.gz";
      sha256 = "sha256-J9HGD3PSavZQwh2eZPbM6isdknZ1M2nkL5WHlYjRju8=";
    };
  };
  yabai-zsh-completions = {
    pname = "yabai-zsh-completions";
    version = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
    src = fetchFromGitHub {
      owner = "Amar1729";
      repo = "yabai-zsh-completions";
      rev = "6e38681a002e13bdcd43f461f73c53b7c11fd4e5";
      fetchSubmodules = false;
      sha256 = "sha256-II00E32Pnt7PO+PcTtWp4NzSUDhQJTgAPw9HdlItbhQ=";
    };
    date = "2023-11-13";
  };
  zpmod = {
    pname = "zpmod";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "z-shell";
      repo = "zpmod";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-vCQOn+8l9DcVJ6XbtHhr7N5IDr2Ht/JRub217ZO96Ok=";
    };
  };
}
