name: "Dev build dev packages"
on:
  pull_request:
  push:
    branches:
      - dev
    paths:
      - "tests/dev.nix"
jobs:
  dev-pacakges:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - flyci-macos-large-latest-m1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Setup cachix
      uses: cachix/cachix-action@v14
      # Don't replace <YOUR_CACHIX_NAME> here!
      with:
        name: 'shanyouli'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: dev nix packages
      run: nix run .#devci
      timeout-minutes: 240

  publish-stable:
    runs-on: ubuntu-latest
    needs:
      - build-packages
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: git configuration
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
      - name: Push stable
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
