name: "Dev build dev packages"
on:
  pull_request:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  pre-work:
    runs-on: ubuntu-latest
    outputs:
      updatepy: ${{ steps.check.outputs.python }}
      updateNvfetcher: ${{ steps.check.outputs.nvfetcher }}
      devTest: ${{ steps.check.outputs.dev }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: hustcer/setup-nu@v3
        with:
          version: "v0.108.0"
      - name: check update
        id: check
        shell: nu {0}
        run: |
          let P = open "./tests/dev.yaml"
          if ($P | get -o dev) {
            echo "dev=true" o>> $env.GITHUB_OUTPUT
          }
          if ($P | get -o "upPy") {
            echo "python=true" o>> $env.GITHUB_OUTPUT
          }
          if ($P | get -o "upNvfetcher") {
            echo "nvfetcher=true" o>> $env.GITHUB_OUTPUT
          }

  update:
    runs-on: ubuntu-latest
    needs: pre-work
    outputs:
      update: ${{ steps.prev_git.outputs.update }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: cachix/install-nix-action@v31
        with:
          # FIXME: https://github.com/NixOS/nix/issues/9889
          extra_nix_config: |
            experimental-features = nix-command flakes configurable-impure-env auto-allocate-uids
      - name: Prepare github bot
        id: prev_git
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -B test-dev
          if [[ '${{ needs.pre-work.outputs.updatepy }}' == 'true' || '${{ needs.pre-work.outputs.updateNvfetcher }}' == 'true' ]]; then
            echo "update=true" >> $GITHUB_OUTPUT
            echo "update=true" >> $GITHUB_ENV
          fi
      - name: update src by update.py
        if: needs.pre-work.outputs.updatepy == 'true'
        run: nix run .#updatePy
      - name: update src by nvfetcher
        if: needs.pre-work.outputs.updateNvfetcher == 'true'
        run: |
          cat > secrets.toml <<EOF
          [keys]
          github = "${{ secrets.GITHUB_TOKEN }}"
          EOF
          nix run .#nvfetcher
          rm -f secrets.toml
      - name: Push changes
        if: ${{ env.update == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'test-dev'
          force: true

  dev-pacakges:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    if: ${{needs.update.outputs.update == 'true' || needs.pre-work.outputs.devTest == 'true' }}
    needs:
      - pre-work
      - update
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: pre work
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          if [[ '${{ needs.update.outputs.update }}' == "true" ]]; then
            git fetch
            git checkout test-dev
          else
            git checkout -B test-dev
          fi
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Setup cachix
        uses: cachix/cachix-action@v17
        # Don't replace <YOUR_CACHIX_NAME> here!
        with:
          name: 'shanyouli'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check evaluation
        run: nix flake show
      - name: dev nix packages
        if: ${{ needs.pre-work.outputs.devTest == 'true' }}
        run: nix run .#devci
        timeout-minutes: 240
      - name: build all packages
        if: ${{ needs.pre-work.outputs.devTest != 'true' }}
        run: nix run .#ci
        timeout-minutes: 240
      - name: modify code
        id: modify_code
        run: |
          if git status | grep "modified" ; then
            echo "MY_MODIFY=true" >> $GITHUB_ENV
            echo "MY_MODIFY=true" >> $GITHUB_OUTPUT
            git fetch origin
            if git ls-remote origin refs/heads/temp-testdev-${{ matrix.os }} | grep temp-testdev ; then
              git push origin --delete temp-testdev-${{ matrix.os }}
            fi
          fi
      - name: Commit back to repository
        if: ${{ env.MY_MODIFY  == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'auto: update package hashes ${{ matrix.os }}'
          create_branch: true
          branch: temp-testdev-${{ matrix.os }}

  publish-dev:
    runs-on: ubuntu-latest
    needs:
      - pre-work
      - dev-pacakges
      - update
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: pre work
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          if [[  '${{ needs.update.outputs.update }}' == "true" ]]; then
            git fetch origin
            git checkout test-dev
          else
            git checkout -B test-dev
          fi
      - name: Merge os chanages
        if: needs.dev-packages.outputs.MY_MODIFY == 'true'
        run: |
          git fetch origin
          echo "Getting information about all branches."
          echo "Merging of branch temp-testdev-macos-latest"
          if git ls-remote origin refs/heads/temp-testdev-macos-latest | grep temp-testdev-macos-latest ; then
            if git diff origin/temp-testdev-macos-latest | grep "+++"; then
              git checkout origin/temp-testdev-macos-latest
              echo "MY_MERGE_MACOS=true" >> $GITHUB_ENV
            fi
          fi
      - uses: hustcer/setup-nu@v3
        with:
          version: "v0.108.0"
      - name: turn off dev.yaml
        if: ${{ needs.pre-work.outputs.devTest == 'true' ||  needs.update.outputs.update == 'true' }}
        shell: nu {0}
        run: |
          let info = {
            dev: false,
            upPy: false,
            upNvfetcher: false,
            apps: ["darwin file -> darwin-apps-xx", "python file -> python-apps-xx", "firefox-addons -> firefox-addons-xx", "fish file -> fish-xx", "emacsPackages -> emacs-packages-xx",  "lua file -> lua-apps-x"]
          }
          $info | to yaml | save -f ./tests/dev.yaml
      - name: commit dev.yaml
        if: ${{ needs.pre-work.outputs.devTest == 'true' }}
        run: |
          git add ./tests/dev.yaml
          git commit -m "feat: turn off dev"
      - name: merge-to-master with macos-latest
        if: ${{ env.MY_MERGE_MACOS == 'true'}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'test-dev'
          force: true
      - name: merge ubuntu chanages
        if: needs.dev-packages.outputs.MY_MODIFY == 'true'
        run: |
          git fetch origin
          git checkout $MY_TARGET_BRANCH
          git pull
          echo "Merging of branch temp-testdev-ubuntu-latest"
          if git ls-remote origin refs/heads/temp-testdev-ubuntu-latest | grep temp-testdev-ubuntu-latest ; then
            if git diff origin/temp-testdev-ubuntu-latest | grep "+++"; then
              git checkout origin/temp-testdev-ubuntu-latest
              echo "MY_MERGE_LINUX=true" >> $GITHUB_ENV
            fi
          fi
      - name: merge-to-master with macos-latest
        if: ${{ env.MY_MERGE_LINUX == 'true'}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'test-dev'
          force: true
      - name: prev
        run: |
          git fetch
          git checkout test-dev
      - name: Push dev
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'dev'
          force: true
      - name: Push master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
          force: true
