name: "Dev build dev packages"
on:
  pull_request:
  push:
    branches:
      - dev
    paths:
      - "tests/dev.nix"
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - flyci-macos-large-latest-m1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: dev nix packages
      run: nix run .#devci
      timeout-minutes: 240
