name: Update src and lock

on:
  schedule:
    # run this daily at 8am UTC, or roughly 4am eastern
    - cron: '15 21 * * 5'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      # - uses: styfle/cancel-workflow-action@0.7.0
      #   with:
      #     access_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: cachix/install-nix-action@v30
        with:
          # FIXME: https://github.com/NixOS/nix/issues/9889
          extra_nix_config: |
            experimental-features = nix-command flakes configurable-impure-env auto-allocate-uids
      - name: Prepare flakebot branch
        run: |
          git config --local user.email "flakebot@users.noreply.github.com"
          git config --local user.name "flakebot"
          git checkout -B flakebot
      - name: Backup before auto-update to another branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: flakebot
          force: true
      - name: Update and commit lockfile
        run: nix flake update --commit-lock-file
      - name: Update nvfetcher src
        run: |
          cat > secrets.toml <<EOF
          [keys]
          github = "${{ secrets.GITHUB_TOKEN }}"
          EOF
          nix run .#nvfetcher
      - name: update bbdown src
        run: nix run .#bbdownDeps
      - name: update src by update.py
        run: nix run .#updatePy
      - name: Current Time
        run: echo "CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: flakebot
          force: true
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: 'flakebot'
          PULL_REQUEST_BRANCH: 'master'
          MAINTAINER_CANT_MODIFY: true
          PASS_IF_EXISTS: true
          PASS_ON_ERROR: true
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_TITLE: 'Update src and lock'
      - name: Trigger second workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "trigger-second-workflow"}'
